# DNA-Net Configuration File

# Model Architecture
model:
  in_channels: 3
  base_channels: 64
  scales: [1, 2, 4]

# Training Settings
training:
  num_epochs: 100
  batch_size: 4
  val_batch_size: 1
  num_workers: 4
  
  # Learning rate
  learning_rate: 0.0002
  lr_scheduler: 'cosine'  # 'cosine', 'step', or 'plateau'
  lr_decay_epochs: [50, 75]
  lr_decay_rate: 0.1
  min_lr: 0.000001
  
  # Optimizer
  optimizer: 'adam'  # 'adam' or 'adamw'
  weight_decay: 0.0001
  betas: [0.9, 0.999]
  
  # Gradient clipping
  clip_grad_norm: 1.0

# Loss Configuration
loss:
  l1_weight: 1.0
  l2_weight: 0.0
  charbonnier_weight: 0.0
  edge_weight: 0.05
  ssim_weight: 0.1
  perceptual_weight: 0.0  # Set > 0 to use perceptual loss (requires VGG)
  rlp_weight: 0.1

# Data Settings
data:
  # For single dataset
  train_rainy_dir: '/home/trusted-service-user/.cache/kagglehub/datasets/quangtrnminh/rain13kdataset/versions/1/train/train/Rain13K/input'
  train_clean_dir: '/home/trusted-service-user/.cache/kagglehub/datasets/quangtrnminh/rain13kdataset/versions/1/train/train/Rain13K/target'
  val_rainy_dir: '/home/trusted-service-user/.cache/kagglehub/datasets/quangtrnminh/rain13kdataset/versions/1/test/test/Rain100H/input'
  val_clean_dir: '/home/trusted-service-user/.cache/kagglehub/datasets/quangtrnminh/rain13kdataset/versions/1/test/test/Rain100H/target'

  # For mixed day/night dataset
  use_mixed_dataset: false
  train_day_rainy_dir: 'data/train/day/rainy'
  train_day_clean_dir: 'data/train/day/clean'
  train_night_rainy_dir: 'data/train/night/rainy'
  train_night_clean_dir: 'data/train/night/clean'
  val_day_rainy_dir: 'data/val/day/rainy'
  val_day_clean_dir: 'data/val/day/clean'
  val_night_rainy_dir: 'data/val/night/rainy'
  val_night_clean_dir: 'data/val/night/clean'
  day_night_ratio: 1.0  # Ratio of day to night samples
  
  # Augmentation
  patch_size: 256
  augment: true

# Evaluation Metrics
metrics:
  - psnr
  - ssim
  - mae

# Checkpoint Settings
checkpoint:
  save_dir: 'checkpoints'
  save_freq: 5  # Save every N epochs
  keep_last_n: 5  # Keep last N checkpoints
  save_best: true  # Save best model based on validation metric
  best_metric: 'psnr'  # Metric for determining best model

# Logging
logging:
  log_dir: 'logs'
  log_freq: 50  # Log every N iterations
  val_freq: 1  # Validate every N epochs
  tensorboard: true
  save_images: true
  num_val_images: 5  # Number of validation images to save

# Device Settings
device:
  use_gpu: true
  gpu_ids: [0]  # List of GPU IDs to use
  
# Reproducibility
seed: 42
deterministic: true

# Resume Training
resume:
  enabled: false
  checkpoint_path: ''
  
# Testing
test:
  checkpoint_path: ''
  test_rainy_dir: '/home/trusted-service-user/.cache/kagglehub/datasets/quangtrnminh/rain13kdataset/versions/1/test/test/Test100/input'
  test_clean_dir: '/home/trusted-service-user/.cache/kagglehub/datasets/quangtrnminh/rain13kdataset/versions/1/test/test/Test100/target'
  output_dir: 'results'
  save_images: true
